version: "3"
services:
  app:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./app:/app
    command: jupyter-notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    tty: true
    
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]